export const CREATE_OR_SIGNIN_USER_SUCCESS = 'CREATE_OR_SIGNIN_USER_SUCCESS';
export const CREATE_OR_SIGNIN_USER_FAIL = 'CREATE_OR_SIGNIN_USER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOADING = 'LOADING';