export const USERNAME_TEXT_CHANGE = 'USERNAME_TEXT_CHANGE';
export const CHECKING_USERNAME = 'CHECKING_USERNAME';
export const USERNAME_TEST_RESULT = 'USERNAME_TEST_RESULT';
export const CREATE_OR_SIGNIN_USER_SUCCESS = 'CREATE_OR_SIGNIN_USER_SUCCESS';
export const CREATE_OR_SIGNIN_USER_FAIL = 'CREATE_OR_SIGNIN_USER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOADING = 'LOADING';